### ISSUE TITLE
About Bowtie2 setings

### ISSUE THREAD

**Issue by iamnotaNL** [johnssproul/RepeatProfiler#10]
Hello, 
I met some strange problems when using the program. 
For example, 
command "repeatprof profile -p reference.fa  reads  --'--very-fast-local' " can run very fast, but "logfile.log" showed "Bowtie2 alignment settings: --very-sensitive-local".  
However, 
command "repeatprof profile -p reference.fa  reads  --very-fast-local " can run very very slow, but "logfile.log" showed "Bowtie2 alignment settings: --very-fast-local".
Could you please help me check the issues?
Thanks.

**Comment by johnssproul** [comment]
Thank you for submitting this issue. I can see now that our table describing optional flags in the ReadMe was confusing for the bowtie preset options such that if followed exactly there would be two extra leading dashes in the flag. A valid use of the flag would just have two leading dashes like '--very-fast-local' as in your second example. Also, our use of single quotes (here and in the ReadMe) was just to delimit the command from the text of the explanation, so they should not be included in the command. The ReadMe table has been updated to remove redundant dashes in the second column.

Regarding the behavior you noticed -- if an incorrect syntax is entered for this particular flag it won't crash the run, rather it will just proceed with the RepeatProfiler default bowtie command of '--very-sensitive-local'. We should really add a warning to the log to alert the user of this behavior (now on our list for the next update). So in the first run you described, that is why the log file reports '--very-sensitive-local', the program just didn't understand the syntax of the flag and ran with the default. The flag in your second run would have been understood, and the log file reflects that. In terms of how long the run took in each case, it does seem puzzling that the '--very-fast-local' ran very slowly compared to '--very-sensitive-local' but I am not sure why. I just did a test with a small data set and '--very-sensitive-local' took ~2 minutes longer to run than '--very-fast-local'. I don't know how much variation to expect in the different bowtie presets across different data sets. Were any other processes were running on that could compete for resources in one run, but not the other? Presumably the commands for each run (including optional flags) were identical otherwise, yes? In short, use the second syntax you described when using this flag. If all else is equal the explanation for run time would seemingly lie in how bowtie is interacting with your particular data set, or differences in computing resources or command structure. If run-time continues to be strange, perhaps you can send examples of full commands and a description of your data and we can try to sort things out further. Thanks again for the feedback and let me know if you continue to have questions.
-John

**Comment by iamnotaNL** [comment]
Hi John, thanks for your reply. The program now seems all ok.
