### ISSUE TITLE
Fastq/fasta File format error

### ISSUE THREAD

**Issue by majie5976** [johnssproul/RepeatProfiler#4]
Hi @johnssproul, 
Thanks for providing wonderful tool to the TE world. I'm quite interested to use RepeatProfiler for my analysis. But encountering same problem again and again for input fastq/reference fasta file format error. Even I double checked using *fastq.gz compressed and *fastq uncompressed file, the error exist as it is, 
 ThinkStation-P920:~/moin/RepeatProfiler$  ./repeatprof profile -p Viridiplantae_v3.0_ALL_protein-domains.fasta /home/majie/moin/RepeatProfiler/foldOne.fastq.gz
Error as below,
"The path to the paired reads file(s) is incorrect, or the file(s) is/are in a unsupported format
Make sure the path is correct (including checking for blanks). Make sure read files have '.fastq' or '.fq' extensions. Compressed (i.e., '.gz') formats also accepted (e.g., 'fastq.gz')"
I don"t know how to resolve this issue, can you help to find solution for this.
Thanks,
Regards
majie

**Comment by johnssproul** [comment]
Dear majie,

Thank you for your note. Thank you also for testing RepeatProfiler—I hope it will be useful for your analysis if we can solve the error. :) 

I have two suggestions that may help you avoid this error. 

First, when you provide the path to the reads RepeatProfiler expects you to give the path to the folder containing the read file(s). It looks like perhaps you provided the full path of the read file. (Or I could be wrong, you have a folder named ‘foldOne.fastq.gz’, but that looks like it could be a file name given the extension.)

Second, are you analyzing paired-reads, or single-end reads? If you use the -p flag, this tells RepeatProfiler to expect paired-reads (i.e., two files)  for each sample being analyzed. If using paired reads, the file names for each pair should be identical except for having _R1 or _R2 before the extension (e.g., 'foldOne_R1.fastq.gz' and 'foldOne_R2.fastq.gz’) If you are analyzing unpaired reads, the file names should not matter as long as they have the a valid extension. If you are analyzing single-end reads, you should use ‘-u' instead of ‘-p' to tell RepeatProfiler to expect single-end read files. It looks like perhaps you are analyzing one file of single-end reads called ‘foldOne.fastq.gz’, if so, you should use ‘-u'. 

Am I understanding your run correctly? If so, try this command:

ThinkStation-P920:~/moin/RepeatProfiler$ ./repeatprof profile -u Viridiplantae_v3.0_ALL_protein-domains.fasta /home/majie/moin/RepeatProfiler

If I am not understanding your run correctly, perhaps you can tell me more about the reads you are trying to run (paired vs unpaired) and give examples of how they are named, I am sure we can solve the error soon.

Kind regards,

John

**Comment by majie5976** [comment]
Hi @johnssproul,
Many Thanks for your well explained answer, That was my mistake I used Interleaved fastq (PE) file instead of separate two fastq files as a input. That problem got fixed, But there is an issue while using already available TE database. Error pasted below,
ThinkStation-P920:~/moin/RepeatProfiler$ ./repeatprof profile -p referenceLo.fasta /home/majie/transposon/seqtk/profiler
generating symlinks
Please make sure the file of references ends in empty line (i.e., unix formatted). You can use tool like dos2unix to confirm unix format.
In the mean while, When I used Repeatexplorer2 output as a reference it worked perfectly for satDNAs and Non-LTR elements.
Looking forward for possible solution of above mentioned issue.
Thanks,
Best regards,
Majie

**Comment by johnssproul** [comment]
Hi Majie, glad to hear the error with the reads is resolved. 

The error you are seeing when using the TE database as a reference sequence file usually comes up because RepeatProfiler expects the last line in the FASTA file of references to end with a new line character (i.e., carriage return). Try opening ‘referenceLo.fasta’ in a text editor, going to the last line and entering a carriage return at the end of that line (if one isn’t already present), saving the file, and rerunning your same command. Let me know if that doesn’t solve the problem. 

That’s great to hear you were able to make profiles directly from RepeatExplorer output. We find this a useful approach in groups with poor representation in existing repeat databases, because repeats in such groups are unlikely to share enough sequence similarity with repeats in databases to produce many informative profiles. Analyzing repeats obtained from de novo assembly of the same data you intend to analyze in RepeatProfiler is a good starting point for exploring repeat dynamics in non-model groups. 

Cheers,

John

**Comment by majie5976** [comment]
Hi @johnssproul,
That issue got fixed and it's working smoothly now. Thanks for your cooperation!
Best Regards,
Majie
