### ISSUE TITLE
Run summary

### ISSUE THREAD

**Issue by mylena-s** [johnssproul/RepeatProfiler#7]
Hi John!
Congrats for the program! I found it very easy to use and it is very well explained in the wiki.
However, I have one question about the run summary file, specifically the percent_mapped column. What does this column contain? is it the percentage of reads that mapped (reads that mapped *100/ total number of reads in both fastq? I am asking because I also read the bowtie log and I cannot make sense of this column.
For ex. I mapped several sequences with repeatprofiler and for one of the references a value of 5,76 is found in this column, meanwhile the bowtie log shows the following:
99999999 reads; of these:
  99999999 (100.00%) were paired; of these:
    95591873 (95.59%) aligned concordantly 0 times
    44660 (0.04%) aligned concordantly exactly 1 time
    4363466 (4.36%) aligned concordantly >1 times
    ----
    95591873 pairs aligned concordantly 0 times; of these:
      74 (0.00%) aligned discordantly 1 time
    ----
    95591799 pairs aligned 0 times concordantly or discordantly; of these:
      191183598 mates make up the pairs; of these:
        190840460 (99.82%) aligned 0 times
        2891 (0.00%) aligned exactly 1 time
        340247 (0.18%) aligned >1 times
**4.58% overall alignment rate**

How could a reference show a higher % of reads mapped than the overal of reads mapped to all references?

Thanks in advance,

Cheers
Mylena

**Comment by johnssproul** [comment]
Hi Mylena -- thanks for the kind words and for checking out RepeatProfiler. Glad it was easy to get running! Thanks very much for raising this issue. As I recall we need to mine information from the BAM files in order to calculate per-reference mapping rates, so there may be some nuance in the definition of that column that we need to clarify in the docs. It is also possible a bug crept in during a previous update. I will look back at the code -- more soon. 
John

**Comment by johnssproul** [comment]
Hi Mylena, it turns out there was a bug. During per-reference coverage calculation, runs with paired-end reads were being treated like single-end read runs. This meant that coverage estimates in the summary table for paired-end data were 2-fold overestimates, while estimates for single-end data runs were correct. Am I correct to presume you were running with paired-end data? We will do some more testing and prepare an update in the next few days. I'll send a note and close the issue when it's ready. Sorry for any inconvenience, and many thanks for raising this issue!
John

**Comment by mylena-s** [comment]
Hi John,
Yes, you are correct. I was using paired-end reads. I am happy to hear that you found the bug. 
I will be expecting the update! Thank you !

Cheers
Mylena

**Comment by johnssproul** [comment]
Hi Mylena, the latest update fixes the overestimate in the summary table with paired reads. Note that if you are updating through Homebrew this fix will be in the next update, but isn't ready quite yet. Cloning the repository (or just replacing the scripts/map_reads.sh file in your RepeatProfiler folder) should fix the bug. Thanks again for reaching out and let us know if you have other issues.  -John
